load_data:
  save_dir: './data'
  workers: 4

train:
  arch_name: "resnet20"  # Select ResNet architecture one from ['resnet20', 'resnet32', 'resnet44', 'resnet56', 'resnet110', 'resnet1202']
  epochs: 182
  batch_size: 128
  learning_rate: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  lr_scheduler_milestones: [91, 136]

save_model:
  saved_model_dir: './saved_models'
  save_checkpoint_epoch: 10

